### ISSUE TITLE
Changing microphone while it is disabled / rapidly changing microphone device permanently disables microphone, spams chat and lags game.

### ISSUE THREAD

**Issue by Orgamorsh** [Towodile/SculkMicrophoneMod#1]
Changing setting spams chat with "Microphone Activated" and lags game.

**To Reproduce**
Set up microphone in settings

**Expected behavior**
Mod sets settings once

**Screenshots**

**Additional context**
I do have simple voice chat installed. And restarting the game fixes it.

**Comment by Towodile** [comment]
I failed to reproduce this bug by *only* changing the settings, however I did manage to do it by taking a few extra steps:
1. Disable the microphone.
2. Select a different input device.
3. Enable the microphone.

So I'll change this issue's title to:
*"Changing microphone while it is disabled spams chat and lags game."*

The bug (as I described) is now fixed, so this issue will be closed. If this bug somehow persists, please create a new issue with an accurate description of what exactly you are doing when it occurs. A fixed version will be released asap.
